### ISSUE TITLE
Features for Release

### ISSUE THREAD

**Issue by lgarron** [cubing/alg.cubing.net#3]
- [x] URL updating.
- [ ] Push URL onto history after 10 seconds. (#28)
- [x] Pretty URLs.
- [x] Sharing.
- [x] Textarea Placeholders.
- [x] Reduce logging
- [ ] Parsing feedback (#22)
- [x] Playback controls
- [x] Cube size
- [x] Title
- [x] Reset button (#14)
- [ ] Color scheme validation (#23)
- [x] Properly handle "solution" type. `wontfix` (let's keep it simple)
- [ ] Logo (#27)

Bugs:
- [x] Scrobbling
- [ ] Color scheme. (#23)
- [x] Scramble/alg wrapping (#25)
- [ ] angular.js doesn't recognize `no-trim` on `textarea`s.

Maybe:
- [ ] AlgTyper mode (#19)
- [x] Full-page animation mode.
- [x] Highlight current move. (#21)
